name: php_codesniffer_plugin
version: 0.0.1
language: 
description: PHP_CodeSniffer is an essential development tool that ensures your code remains clean and consistent.
tags:
 - php
 - codesniffer
 - code
 - format
 - analyzer
 - sniffer
 - plugin

public: true

# clone_in_docker: false

outputs:
  - name: FLOW_PHP_CODE_SNIFFER_WARNING_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_ERROR_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_FILE_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_LOG_PATH

script_path: ./run.sh
