name: php_codesniffer_plugin
version: 0.0.1
language: php
description: "
  用来检查代码是否有违反一组预先设置好的编码标准的一个包，它是确保你的代码简洁一致的必不可少的开发工具，还可以帮助程序员减少一些语义错误
"
tags:
 - php
 - codesniffer
 - code
 - format
 - analyzer
 - sniffer
 - plugin

public: true

# clone_in_docker: false

outputs:
  - name: FLOW_PHP_CODE_SNIFFER_WARNING_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_ERROR_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_FILE_COUNT
  - name: FLOW_PHP_CODE_SNIFFER_LOG_PATH

script_path: ./run.sh
